### ISSUE TITLE
cli: "owners"

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/npm-owner#1]
I think it would be safe to use just `owners` as the first argument

**Comment by doowb** [comment]
Do you mean as what the tool is named? Like how your `list-methods` is run with just `methods`?

**Comment by jonschlinkert** [comment]
just what the bin/file is named, and the command that is used to run it. the repo name is fine

**Comment by doowb** [comment]
Closed by https://github.com/doowb/npm-owner/commit/f3edd08ce92ca0d3647daac24c147a79274a1978
