### ISSUE TITLE
a couple typos 

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/npm-owner#2]
- "do" instead of "so": https://github.com/doowb/npm-owner/blob/master/bin/npm-owner#L25
- "synchronize": https://github.com/doowb/npm-owner/blob/master/bin/npm-owner#L12

**Comment by doowb** [comment]
Thanks... the first one is just a place holder here. I knew the second one looked weird... I'm horrible at spelling :wink:

**Comment by jonschlinkert** [comment]
everyone has typos! just trying to help

**Comment by doowb** [comment]
Closed by https://github.com/doowb/npm-owner/commit/f3edd08ce92ca0d3647daac24c147a79274a1978
